export const PROJECTS = [
    {
        slug: 'grievanceForum',
        logoSrc: '/images/work/project/grievanceForum/GrievanceForum.png',
        logoWidth: { LARGE: 1080, MEDIUM: 1080, COMPACT: 600 },
        heroWidth: 1080,
        desc: 'portfolio.work.grievanceforum.desc.short',
        longDesc: 'portfolio.work.grievanceforum.desc.long',
        compactDesc: null,
        overviewDescs: [
            'portfolio.work.grievanceforum.desc.long',
            'portfolio.featured.grievanceforum.desc',
        ],
        previewImages: [
            '/images/work/project/grievanceForum/preview_0.jpg',
            '/images/work/project/grievanceForum/preview_1.jpg',
            '/images/work/project/grievanceForum/preview_2.jpg',
            '/images/work/project/grievanceForum/preview_3.jpg',
            '/images/work/project/grievanceForum/preview_4.jpg',
            '/images/work/project/grievanceForum/preview_5.jpg',
        ],
        showArrow: true,
        tags: [
            'portfolio.work.tags.web_product',
            'portfolio.work.tags.mobile_compatibility',
            'portfolio.work.tags.nodejs',
            'portfolio.work.tags.expressjs',
        ],
        features: [
            { icon: 'fa-solid fa-paper-plane', title: 'portfolio.work.grievanceforum.f1.title', desc: 'portfolio.work.grievanceforum.f1.desc' },
            { icon: 'fa-solid fa-bell', title: 'portfolio.work.grievanceforum.f2.title', desc: 'portfolio.work.grievanceforum.f2.desc' },
            { icon: 'fa-solid fa-chart-line', title: 'portfolio.work.grievanceforum.f3.title', desc: 'portfolio.work.grievanceforum.f3.desc' },
            { icon: 'fa-solid fa-tags', title: 'portfolio.work.grievanceforum.f4.title', desc: 'portfolio.work.grievanceforum.f4.desc' },
            { icon: 'fa-solid fa-magnifying-glass', title: 'portfolio.work.grievanceforum.f5.title', desc: 'portfolio.work.grievanceforum.f5.desc' },
            { icon: 'fa-solid fa-mobile-screen-button', title: 'portfolio.work.grievanceforum.f6.title', desc: 'portfolio.work.grievanceforum.f6.desc' },
            { icon: 'fa-solid fa-user', title: 'portfolio.work.grievanceforum.f7.title', desc: 'portfolio.work.grievanceforum.f7.desc' },
            { icon: 'fa-solid fa-shield-halved', title: 'portfolio.work.grievanceforum.f8.title', desc: 'portfolio.work.grievanceforum.f8.desc' },
            { icon: 'fa-solid fa-bookmark', title: 'portfolio.work.grievanceforum.f9.title', desc: 'portfolio.work.grievanceforum.f9.desc' },
            { icon: 'fa-solid fa-file-pen', title: 'portfolio.work.grievanceforum.f10.title', desc: 'portfolio.work.grievanceforum.f10.desc' },
            { icon: 'fa-solid fa-user-secret', title: 'portfolio.work.grievanceforum.f11.title', desc: 'portfolio.work.grievanceforum.f11.desc' },
            { icon: 'fa-solid fa-circle-check', title: 'portfolio.work.grievanceforum.f12.title', desc: 'portfolio.work.grievanceforum.f12.desc' },
        ],
        techStack: [
            { name: 'Node.js', icon: 'fa-brands fa-node-js', color: 'text-green-500' },
            { name: 'Express.js', icon: 'fa-brands fa-node', color: 'text-portfolio-300' },
            { name: 'MySQL', icon: 'fa-solid fa-database', color: 'text-blue-400' },
            { name: 'EJS', icon: 'fa-solid fa-code', color: 'text-yellow-500' },
            { name: 'HTML/CSS', icon: 'fa-brands fa-html5', color: 'text-orange-500' },
            { name: 'JavaScript', icon: 'fa-brands fa-js', color: 'text-yellow-400' },
        ],
        githubRepo: 'ManojTGN/GrievanceForum',
        npmLink: null,
    },
    {
        slug: 'cGrafix',
        logoSrc: '/images/work/project/cGrafix/cGrafix.png',
        logoWidth: { LARGE: 1080, MEDIUM: 1080, COMPACT: 600 },
        heroWidth: 1080,
        desc: 'portfolio.work.cgrafix.desc',
        longDesc: null,
        compactDesc: null,
        overviewDescs: [
            'portfolio.featured.cgrafix.desc',
        ],
        previewImages: [
            '/images/work/project/cGrafix/preview_0.jpg',
            '/images/work/project/cGrafix/preview_1.jpg',
            '/images/work/project/cGrafix/preview_2.jpg',
        ],
        showArrow: true,
        tags: [
            'portfolio.work.tags.library',
            'portfolio.work.tags.pure_c',
        ],
        features: [
            { icon: 'fa-solid fa-cube', title: 'portfolio.work.cgrafix.f1.title', desc: 'portfolio.work.cgrafix.f1.desc' },
            { icon: 'fa-solid fa-shapes', title: 'portfolio.work.cgrafix.f2.title', desc: 'portfolio.work.cgrafix.f2.desc' },
            { icon: 'fa-solid fa-font', title: 'portfolio.work.cgrafix.f3.title', desc: 'portfolio.work.cgrafix.f3.desc' },
            { icon: 'fa-solid fa-image', title: 'portfolio.work.cgrafix.f4.title', desc: 'portfolio.work.cgrafix.f4.desc' },
            { icon: 'fa-solid fa-book', title: 'portfolio.work.cgrafix.f5.title', desc: 'portfolio.work.cgrafix.f5.desc' },
            { icon: 'fa-solid fa-feather', title: 'portfolio.work.cgrafix.f6.title', desc: 'portfolio.work.cgrafix.f6.desc' },
        ],
        techStack: [
            { name: 'Pure C', icon: 'fa-solid fa-c', color: 'text-blue-400' },
            { name: 'Windows API', icon: 'fa-brands fa-windows', color: 'text-blue-500' },
            { name: 'Makefile', icon: 'fa-solid fa-gears', color: 'text-portfolio-300' },
        ],
        githubRepo: 'ManojTGN/cGrafix',
        npmLink: null,
    },
    {
        slug: 'asciiCam',
        logoSrc: '/images/work/project/asciiCam/asciicam.png',
        logoWidth: { LARGE: 1080, MEDIUM: 1080, COMPACT: 600 },
        heroWidth: 1080,
        desc: 'portfolio.work.asciicam.desc',
        longDesc: null,
        compactDesc: null,
        overviewDescs: null,
        previewImages: ['/images/work/noPreview.jpg'],
        showArrow: false,
        tags: [
            'portfolio.work.tags.opencv',
            'portfolio.work.tags.cpp',
        ],
        features: [
            { icon: 'fa-solid fa-video', title: 'portfolio.work.asciicam.f1.title', desc: 'portfolio.work.asciicam.f1.desc' },
            { icon: 'fa-solid fa-terminal', title: 'portfolio.work.asciicam.f2.title', desc: 'portfolio.work.asciicam.f2.desc' },
            { icon: 'fa-solid fa-bolt', title: 'portfolio.work.asciicam.f3.title', desc: 'portfolio.work.asciicam.f3.desc' },
            { icon: 'fa-solid fa-sliders', title: 'portfolio.work.asciicam.f4.title', desc: 'portfolio.work.asciicam.f4.desc' },
            { icon: 'fa-solid fa-camera-rotate', title: 'portfolio.work.asciicam.f5.title', desc: 'portfolio.work.asciicam.f5.desc' },
            { icon: 'fa-solid fa-palette', title: 'portfolio.work.asciicam.f6.title', desc: 'portfolio.work.asciicam.f6.desc' },
        ],
        techStack: [
            { name: 'C++', icon: 'fa-solid fa-code', color: 'text-blue-400' },
            { name: 'OpenCV', icon: 'fa-solid fa-eye', color: 'text-green-500' },
            { name: 'CMake', icon: 'fa-solid fa-gears', color: 'text-portfolio-300' },
        ],
        githubRepo: 'ManojTGN/AsciiCam',
        npmLink: null,
    },
    {
        slug: 'collision2Djs',
        logoSrc: '/images/work/project/collision2Djs/collision2Djs.png',
        logoWidth: { LARGE: 1080, MEDIUM: 1080, COMPACT: 600 },
        heroWidth: 1080,
        desc: 'portfolio.work.collision2djs.desc',
        longDesc: null,
        compactDesc: null,
        overviewDescs: null,
        previewImages: [
            '/images/work/project/collision2Djs/preview_0.jpg',
            '/images/work/project/collision2Djs/preview_1.jpg',
            '/images/work/project/collision2Djs/preview_2.jpg',
        ],
        showArrow: true,
        tags: [
            'portfolio.work.tags.javascript',
            'portfolio.work.tags.nodejs',
        ],
        features: [
            { icon: 'fa-solid fa-crosshairs', title: 'portfolio.work.collision2djs.f1.title', desc: 'portfolio.work.collision2djs.f1.desc' },
            { icon: 'fa-solid fa-diagram-project', title: 'portfolio.work.collision2djs.f2.title', desc: 'portfolio.work.collision2djs.f2.desc' },
            { icon: 'fa-solid fa-gauge-high', title: 'portfolio.work.collision2djs.f3.title', desc: 'portfolio.work.collision2djs.f3.desc' },
            { icon: 'fa-solid fa-shapes', title: 'portfolio.work.collision2djs.f4.title', desc: 'portfolio.work.collision2djs.f4.desc' },
            { icon: 'fa-solid fa-book-open', title: 'portfolio.work.collision2djs.f5.title', desc: 'portfolio.work.collision2djs.f5.desc' },
            { icon: 'fa-solid fa-plug', title: 'portfolio.work.collision2djs.f6.title', desc: 'portfolio.work.collision2djs.f6.desc' },
        ],
        techStack: [
            { name: 'JavaScript', icon: 'fa-brands fa-js', color: 'text-yellow-400' },
            { name: 'Node.js', icon: 'fa-brands fa-node-js', color: 'text-green-500' },
            { name: 'NPM', icon: 'fa-brands fa-npm', color: 'text-red-500' },
        ],
        githubRepo: 'ManojTGN/Collision2Djs',
        npmLink: 'https://www.npmjs.com/package/collision2djs',
    },
    {
        slug: 'asciiTable',
        logoSrc: '/images/work/project/asciiTable/asciitable.png',
        logoWidth: { LARGE: 480, MEDIUM: 280, COMPACT: 280 },
        heroWidth: 480,
        desc: 'portfolio.work.asciitable.desc',
        longDesc: null,
        compactDesc: 'portfolio.work.asciitable.desc.short',
        overviewDescs: [
            'portfolio.work.asciitable.desc.short',
        ],
        previewImages: [
            '/images/work/project/asciiTable/preview_0.jpg',
            '/images/work/project/asciiTable/preview_1.jpg',
            '/images/work/project/asciiTable/preview_2.jpg',
        ],
        showArrow: true,
        tags: [
            'portfolio.work.tags.terminal',
            'portfolio.work.tags.pure_c',
        ],
        features: [
            { icon: 'fa-solid fa-table', title: 'portfolio.work.asciitable.f1.title', desc: 'portfolio.work.asciitable.f1.desc' },
            { icon: 'fa-solid fa-filter', title: 'portfolio.work.asciitable.f2.title', desc: 'portfolio.work.asciitable.f2.desc' },
            { icon: 'fa-solid fa-arrow-down-a-z', title: 'portfolio.work.asciitable.f3.title', desc: 'portfolio.work.asciitable.f3.desc' },
            { icon: 'fa-solid fa-palette', title: 'portfolio.work.asciitable.f4.title', desc: 'portfolio.work.asciitable.f4.desc' },
            { icon: 'fa-solid fa-keyboard', title: 'portfolio.work.asciitable.f5.title', desc: 'portfolio.work.asciitable.f5.desc' },
            { icon: 'fa-solid fa-hashtag', title: 'portfolio.work.asciitable.f6.title', desc: 'portfolio.work.asciitable.f6.desc' },
        ],
        techStack: [
            { name: 'Pure C', icon: 'fa-solid fa-c', color: 'text-blue-400' },
            { name: 'Terminal', icon: 'fa-solid fa-terminal', color: 'text-green-500' },
            { name: 'Makefile', icon: 'fa-solid fa-gears', color: 'text-portfolio-300' },
        ],
        githubRepo: 'ManojTGN/AsciiTable',
        npmLink: null,
    },
];

export function getProjectBySlug(slug) {
    return PROJECTS.find(p => p.slug === slug) || null;
}
